services:
  backend:
    build: .
    container_name: flight-planner-backend
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/flightdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mysql
    env_file:
      - .env

  frontend:
    build:
      context: ./flight-planner-frontend
      args:
        - VITE_API_BASE_URL=http://localhost:8080/api/v1
    container_name: flight-planner-frontend
    ports:
      - 3000:8080
    depends_on:
      - backend
  
  mysql:
    image: mysql:8.0
    container_name: flight-planner-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=flightdb
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
      