name: Run Maven Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
                
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                    distribution: 'temurin'
                    java-version: '21'
                    cache: 'maven'

            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                    path: ~/.m2
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-maven-

            - name: Run unit tests with Maven
              run: mvn test