name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: flight-planner-app-464807
  REGION: us-central1
  BACKEND_SERVICE: flight-planner-backend
  BACKEND_IMAGE: us-central1-docker.pkg.dev/flight-planner-app-464807/flight-planner-backend/backend

jobs:
  test:
    name: Run Maven Tests
    runs-on: ubuntu-latest

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
            
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
                distribution: 'temurin'
                java-version: '21'
                cache: 'maven'

        - name: Cache Maven packages
          uses: actions/cache@v4
          with:
                path: ~/.m2
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    ${{ runner.os }}-maven-

        - name: Run unit tests with Maven
          run: mvn test
  deploy-backend:
    name: Build & Deploy Spring Boot
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}   

      - name: Set up Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build & Push Docker image
        run: |
          docker build -t $BACKEND_IMAGE .
          docker push $BACKEND_IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $BACKEND_SERVICE \
            --image=$BACKEND_IMAGE \
            --region=$REGION \
            --platform=managed \
            --allow-unauthenticated \
            --add-cloudsql-instances=flight-planner-app-464807:us-central1:flight-planner-sql \
            --set-env-vars="SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }},SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }},SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }},JWT_SECRET=${{ secrets.JWT_SECRET }}"
